spring:
  application:
    name: accesoya-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/accesoya_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false

    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 500
        order_inserts: true
        order_updates: true

  # =====================================================
  # MULTIPART / ARCHIVOS
  # =====================================================

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB

# =====================================================
# ACCESOYA
# =====================================================

accesoya:
  import:
    renipress:
      enabled: false

    openstreetmap:
      enabled: true

    flm-noc:
      enabled: true

# =====================================================
# LIBREOFFICE
# =====================================================

libreoffice:
  executable: 'C:\Program Files\LibreOffice\program\soffice.exe'

# =====================================================
# SEGURIDAD JWT
# =====================================================

security:
  jwt:
    secret: ${JWT_SECRET:AccesoYaDevelopmentSecretKey12345678901234567890}
    expiration-ms: 86400000

# =====================================================
# SERVIDOR
# =====================================================

server:
  port: 8080
